### PR TITLE
[WIP] Just simple replace SuspendProcess to SuspendProcesses

### PR DESCRIPTION
**Pull request by Znack**
Still under development

Fix https://github.com/frontrowed/stratosphere/issues/84

### CODE REVIEW

**Comment by jdreaver** [comment]
Hey @Znack thanks for the PR!

Note that the code you edited is [auto-generated](https://github.com/frontrowed/stratosphere#auto-generation) from the official AWS [JSON schema file](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html). Unfortunately this PR as-is will just be overwritten. 

My usual way of dealing with errors in the schema document is to open a ticket with AWS support. Do you have access to AWS support, or do you need me to open a ticket on our business account?

**Comment by Znack** [comment]
Oh, I supposed only `library-gen` is auto-generated, and my fix in `stratosphere/library/Stratosphere/ResourceAttributes` makes sense :)

Yeah, we have an account and it will be good exprience for me to learn their schema document and talk with support, so I can do it, and in case of trouble I will write you here

**Comment by jdreaver** [comment]
Oh! I'm silly, you are correct. This code is not autogenerated, only the stuff in `library-gen`. I'll merge, thanks again!

**Comment by Znack** [comment]
I could not find any information about `AutoScalingRollingUpdatePolicy` in those specifications :(

As I understood from the docs' structure, `json` doc describes Resources and their property, but rolling update policy is part of Resource attribute, which is the higher level of abstruction, I've attached the screenshot of hierarchy:
image

I hope I didn't miss something important, it is quite late Sunday's evening already :)

**Comment by Znack** [comment]
Just seen you comment 😆 

I've tested my fixes with our template, it is quite big and `SuspendProcesses` meets 5 times their in various values, so hope everything is really correct :)

**Comment by jdreaver** [comment]
Great! Heh, yeah I usually just run new versions of `stratosphere` on our company's various templates as an integration test.

**Comment by Znack** [comment]
Hope this will be enough :)

I also have a great opportunity to compare json output of the same's stack templates from Troposphere and Stratosphere until we haven't migrated to Haskell and I maintain both version. If Python's Troposphere would also make Bools and Ints as Strings, comparing would be perfect :)

**Comment by jdreaver** [comment]
Wait, `troposphere` doesn't make Bools and Ints as Strings? I thought we had to for CloudFormation. You are about to blow my mind right now if that isn't the case haha

**Comment by Znack** [comment]
Yep, Troposphere generate `json` with simple Bools and Ints :)

I thought Stratosphere convert it only in relatively new versions because of some problems with Bool and Int converting to json with Aeson :)

Below is the example of Troposphere on the right and Stratosphere on the left, that's how I compare json files in VSCode:

image

**Comment by jdreaver** [comment]
That's very interesting. I've opened https://github.com/frontrowed/stratosphere/issues/86 to investigate doing that in `stratosphere`, although I'm not sure what advantages that brings just yet :smile:

**Comment by Znack** [comment]
Am I right, that now we can get rid of newtype wrappers `Integer'` and `Bool'`? If so, it will be quite cool and allow to simplify a codebase a lot :)

**Pull request merged**
