### PR TITLE
Use the official specification file from AWS instead of our own custom templates

### PR DESCRIPTION
**Pull request by jdreaver**
See here: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html

So far everything works great. I have the entire spec built and it gets compiled (I haven't committed the generated code to git yet). I found a couple of bugs in the spec and I've opened a support ticket with AWS through my company's account, but I've worked around them for now. 

Now I just need to recover our custom type usage from `Stratosphere.Types`, and fix the examples. I'm also going to refactor the code generator a bit, and remove more dead code.

The one huge downside of this change is a lot of things are going to be renamed. The naming rule I used for a resource or property of type `AWS::X::Y.Z` is `XYZ` (remove the `AWS::` part and just concatenate the rest). For example, the property `AWS::EC2::Instance.Ebs` is called `EC2InstanceEbs`. It's a little verbose for some properties, but it's consistent with official AWS naming and we should probably use their official names going forward.

Another tiny downside is the official spec file uses links to docs rather than doc snippets, so if we want to get our extensive docstrings back we'll need to scrape those doc links.

(cc @MichaelXavier @timmytofu @ababkin @amar47shah in case you guys are interested or have any feedback)

### CODE REVIEW

**Comment by jdreaver** [comment]
I've completed fixing the examples and doing my other misc improvements. I'm going to try this out on a ton of CloudFormation templates I use later, but I committed the generated code so you guys can try too if you want. We should have 100% service coverage for CloudFormation now! (Well, once they fix the bugs in the spec :smile:)

**Comment by MichaelXavier** [comment]
Naming has always been a bit of a rough edge for me with stratosphere. The scraper scripts tend to erase the service name from the final module types, e.g. instead of KinesisStream you get Stream, which will become a problem with the more services you bring onboard since some will have conflicting names. I think I may have even hit this case at some point. Would this get resolved in the new update (github is not making it easy to diff due to the size of the diff)?

Other than that, I don't really care about the type changes especially if it gets on the official path to defining new resources. 100% service coverage sounds amazing. I'm constantly having to submodule and un-submodule the stratosphere project when adding new projects, and it is a little bit trickier to build anyways because of using hpack, so this upgrade sounds well worth it to me :+1:

**Comment by jdreaver** [comment]
Hopefully the new naming scheme works great; it includes everything except the `AWS::` part of names. I only found one name collision (the `AWS::RDS::DBSecurityGroupIngress` resource and the `AWS::RDS::DBSecurityGroup.Ingress` property) and I fixed it [here](https://github.com/frontrowed/stratosphere/blob/5e71b5442bf6a77e37d4467bd06d16e6fb2748d7/gen/src/Gen/Specifications.hs#L112-L122). Since we are at 100% coverage and we only have 1 conflict, I highly doubt we'll hit naming conflicts in the future. If we do hit conflicts, we have a lot of leeway to rename things and it's really easy to do.

Most of the diff is the new auto-generated code, so I bet GIthub has a hard time with it. If you only look at things in the `gen/` directory you'll see the meat of the changes.

There's only a few bugs in the spec, and I have an open ticket with AWS support (Front Row has business level support) to resolve them. They agree with the bugs/solutions I found, so hopefully it doesn't take too long, but I patched around them for now. I'm going to try out this branch on our templates when I get some time and figure out if anything big broke. Refactoring the `stratosphere` examples with the new names was surprisingly easy.

Thanks for the feedback!

**Comment by jdreaver** [comment]
Status update: I've ported all of the Front Row templates over and everything works great. There are zero changes in the resulting JSON files.

AWS support tells me they are fixing all of the errors I found (something like 15 errors in total I think). I've patched around all of them for now, so the generated code shouldn't change once they are fixed in the official spec. Of course, they will probably find more errors that have to be fixed in the coming weeks.

**Comment by amar47shah** [comment]
Have been following this PR via email. Really fantastic!

Also this:
> AWS support tells me they are fixing all of the errors I found (something like 15 errors in total I think)

💯

**Pull request merged**
