### PR TITLE
Fix incorrect type for elb policy Attributes

### PR DESCRIPTION
**Pull request by MichaelXavier**

### CODE REVIEW

**Comment by jdreaver** [comment]
Wow, another great PR!

I'm still unsure about the approach to `NameValuePair`. I think the auto-gen functionality should be used for things that are actually in the CloudFormation docs. I think we should either:
1. Add a type called `NameValuePair` to [`library/Stratosphere/Types.hs`](https://github.com/frontrowed/stratosphere/blob/master/library/Stratosphere/Types.hs)
2. Or, see if just using `[(Text, Text)]` works there. I'm not sure if the auto-gen code will get screwed up by that type or not.

I'll try both of those out right now. In the meantime, I'll merge your other PR that doesn't include `NameValuePair`.

**Comment by jdreaver** [comment]
Also, I'm curious, did you use the `gen/scraper.py` script? Was it useful? I'm really impressed you figured out where to put everything, I didn't document that very well :smile:

**Comment by jdreaver** [comment]
You know what, this PR is fine as-is. I must have misread the CloudFormation ELB policy docs the first time around. Thanks again for the PR!

**Comment by MichaelXavier** [comment]
I did indeed use the scraper script. Very helpful! I had to add in the dependencies key but I found another example that did it.

I could add it to the library dir, I didn't know about the convention so if there's a better place, we can totally do that.

I'm not such a big fan of using really basic types, especially when the fields are known. In fact I may have a few PRs for you in the future where the code is using an `Object` when it could be more specific. Let me know if you need anything from me to fix up this PR even though you merged it.

**Pull request merged**
