### PR TITLE
This adds basic lambda resource, properties and a usage example

### PR DESCRIPTION
**Pull request by ababkin**

### CODE REVIEW

**Comment by jdreaver** [comment]
Awesome, great work!

I think we're missing the [`VpcConfig`](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-vpcconfig) parameter on the `AWS::Lambda::Function` though (docs for that [here](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-vpcconfig.html)). Did you use the [`scraper.py`](https://github.com/frontrowed/stratosphere/blob/master/gen/scraper.py) script to create the file? I wonder if it missed `VpcConfig` somehow.

If you're too busy I can just merge and add it myself, everything else in this PR is super solid.

Thanks!

**Comment by ababkin** [comment]
Two reasons: first, i was testing your vigilance, which you've passed with flying colors :)
second: for all the time i've been using AWS Lambda, i've never used the VPC capability for it, so seeing that it would require an extra Property i've decided to skip it. And yes I've used the `scraper.py` (had to hand tune the generated json a little)
But if all the other resources are at parity with the AWS spec, then I'm all for consistency. 
I will add the parameter to the PR as soon as i get a chance.

**Comment by jdreaver** [comment]
Haha, great! Yeah I just add all the properties because it saves an explanation and fix down the road.

The scraper is very useful, but it definitely requires hand-tuning for all but the most trivial of cases. The best situation would be to acquire the raw files AWS uses for their docs somehow so we don't have to use this roundabout method of generating them.

**Comment by ababkin** [comment]
@jdreaver , this should be good to go

**Comment by jdreaver** [comment]
Yup, thanks!

**Pull request merged**
