### PR TITLE
Adds Trail (AWS::CloudTrail::Trail) resource

### PR DESCRIPTION
**Pull request by timmytofu**

### CODE REVIEW

**Comment by jdreaver** [comment]
Awesome! Did you run the `build-all.sh` script? There are some changes in `library-gen/Stratosphere/Resources.hs` that need to be applied as well (importing the new module, adding to `ResourceProperties`, etc).

**Comment by timmytofu** [comment]
I did run `build.sh`, [this is the diff](https://timtemp.s3.amazonaws.com/library-gen.diff) I get for `library-gen/Stratosphere/Resources.hs` which seems a bit large.

**Comment by jdreaver** [comment]
Oh wow, I'm going to have to look into that. There must be some non-determinism going on with the order of the generated modules. I'll change it to sort modules before we put them in that file. 

In the meantime, do you want to apply this diff to your current PR?

```diff
diff --git a/library-gen/Stratosphere/Resources.hs b/library-gen/Stratosphere/Resources.hs
index fbc9b0d..fa91bf6 100644
--- a/library-gen/Stratosphere/Resources.hs
+++ b/library-gen/Stratosphere/Resources.hs
@@ -68,6 +68,7 @@ import Stratosphere.Resources.VPC as X
 import Stratosphere.Resources.AccessKey as X
 import Stratosphere.Resources.LoadBalancer as X
 import Stratosphere.Resources.ScalingPolicy as X
+import Stratosphere.Resources.Trail as X
 import Stratosphere.Resources.AutoScalingGroup as X
 import Stratosphere.Resources.ScheduledAction as X
 import Stratosphere.Resources.Volume as X
@@ -147,6 +148,7 @@ data ResourceProperties
   | AccessKeyProperties AccessKey
   | LoadBalancerProperties LoadBalancer
   | ScalingPolicyProperties ScalingPolicy
+  | TrailProperties Trail
   | AutoScalingGroupProperties AutoScalingGroup
   | ScheduledActionProperties ScheduledAction
   | VolumeProperties Volume
@@ -264,6 +266,8 @@ resourcePropertiesJSON (LoadBalancerProperties x) =
   [ "Type" .= ("AWS::ElasticLoadBalancing::LoadBalancer" :: String), "Properties" .= toJSON x]
 resourcePropertiesJSON (ScalingPolicyProperties x) =
   [ "Type" .= ("AWS::AutoScaling::ScalingPolicy" :: String), "Properties" .= toJSON x]
+resourcePropertiesJSON (TrailProperties x) =
+  [ "Type" .= ("AWS::CloudTrail::Trail" :: String), "Properties" .= toJSON x]
 resourcePropertiesJSON (AutoScalingGroupProperties x) =
   [ "Type" .= ("AWS::AutoScaling::AutoScalingGroup" :: String), "Properties" .= toJSON x]
 resourcePropertiesJSON (ScheduledActionProperties x) =
@@ -316,6 +320,7 @@ resourceFromJSON n o =
          "AWS::IAM::AccessKey" -> AccessKeyProperties <$> (o .: "Properties")
          "AWS::ElasticLoadBalancing::LoadBalancer" -> LoadBalancerProperties <$> (o .: "Properties")
          "AWS::AutoScaling::ScalingPolicy" -> ScalingPolicyProperties <$> (o .: "Properties")
+         "AWS::CloudTrail::Trail" -> TrailProperties <$> (o .: "Properties")
          "AWS::AutoScaling::AutoScalingGroup" -> AutoScalingGroupProperties <$> (o .: "Properties")
          "AWS::AutoScaling::ScheduledAction" -> ScheduledActionProperties <$> (o .: "Properties")
          "AWS::EC2::Volume" -> VolumeProperties <$> (o .: "Properties")
```

**Comment by timmytofu** [comment]
Whoops, looks like you beat me to it, but yeah, there's library-gen with just the Trail-relevant stuff. The rest look like they might just be things reordered, tough to tell. Good like that, or should I fixup and force push?

**Comment by jdreaver** [comment]
This is fine how it is. Thanks again for the PR!

**Pull request merged**
