### PR TITLE
Adds UserName property to (IAM) User resource

### PR DESCRIPTION
**Pull request by timmytofu**
supported now per http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-iam-user.html

### CODE REVIEW

**Comment by jdreaver** [comment]
Hey, thanks for the PR! The `library-gen` folder is actually auto-generated based off of the files in `gen/models`. In particular, the IAM user resource is in [this file](https://github.com/frontrowed/stratosphere/blob/master/gen/models/resources/iam-user.json). 

I'll make the change and attribute the commit to you.

**Comment by jdreaver** [comment]
I added this on master. Let me know if it works for you, or if I messed something up! (I'll be on vacation for the next 5 days but I might have a couple hours here and there).

**Comment by timmytofu** [comment]
Works for me! I should've noticed that, I'll make changes thusly in the future.

I think with the changes you made a few weeks ago the [upperbound on stackage](https://github.com/fpco/stackage/blob/master/build-constraints.yaml#L2469) can be removed?

**Comment by jdreaver** [comment]
Great!

I actually just pinged the stackage issue that caused the upper bound. I
think it will be removed soon.

Do you want me to make a release, or are you fine using the git ref for
now?

**Comment by timmytofu** [comment]
I'm fine waiting. I made another tiny PR to bump the subminor version so I can set a confident lowerbound (e.g. it'll fail for unsatisfiable bounds if I forget to add the git ref as a package).

**Pull request closed without merging**
